version: '3.8'
services:

    php-apache:
        container_name: php-apache
        build:
            context: ./php
            dockerfile: Dockerfile
        depends_on:
            - mysql
        volumes:
            - ./php/src:/var/www/html/
        ports:
            - 8000:80

    mysql:
        image: mysql:8
        container_name: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
            MYSQL_DATABASE: MYSQL_DATABASE
            MYSQL_USER: MYSQL_USER
            MYSQL_PASSWORD: MYSQL_PASSWORD
        ports:
            - "9906:3306"
    
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - '8080:80'
        restart: always
        environment:
            PMA_HOST: mysql
        depends_on:
            - mysql
    
    maildev:
        image: djfarrelly/maildev
        container_name: maildev
        ports:
            - 8001:80    